run:
  skip-dirs-use-default: false
linters-settings:
  dupl:
    threshold: 200
  errcheck:
    check-type-assertions: true
  exhaustruct:
    include:
      # No zero values for param structs.
      - 'connectrpc\.com/otelconnect\..*[pP]arams'
  forbidigo:
    forbid:
      - '^fmt\.Print'
      - '^log\.'
      - '^print$'
      - '^println$'
      - '^panic$'
  importas:
    no-unaliased: true
    alias:
      - pkg: connectrpc.com/connect
        alias: connect
      - pkg: connectrpc.com/otelconnect/internal/gen/observability/ping/v1
        alias: pingv1
  godox:
    # TODO, OPT, etc. comments are fine to commit. Use FIXME comments for
    # temporary hacks, and use godox to prevent committing them.
    keywords: [FIXME]
  varnamelen:
    ignore-decls:
      - T any
      - i int
      - wg sync.WaitGroup
linters:
  enable-all: true
  disable:
    - cyclop            # covered by gocyclo
    - depguard          # unnecessary for small libraries
    - execinquery       # deprecated since golangci v1.58
    - funlen            # rely on code review to limit function length
    - gocognit          # dubious "cognitive overhead" quantification
    - gofumpt           # prefer standard gofmt
    - goimports         # rely on gci instead
    - gomnd             # some unnamed constants are okay
    - inamedparam       # convention is not followed
    - ireturn           # "accept interfaces, return structs" isn't ironclad
    - lll               # don't want hard limits for line length
    - maintidx          # covered by gocyclo
    - mnd               # status codes are clearer than constants
    - nlreturn          # generous whitespace violates house style
    - nonamedreturns    # named returns are fine; it's *bare* returns that are bad
    - protogetter       # too many false positives
    - testpackage       # internal tests are fine
    - wrapcheck         # don't _always_ need to wrap errors
    - wsl               # generous whitespace violates house style
issues:
  exclude:
    # Don't ban use of fmt.Errorf to create new errors, but the remaining
    # checks from err113 are useful.
    - "do not define dynamic errors, use wrapped static errors instead: .*"

  exclude-rules:
    # If-else is clearer than switch here.
    - linters: [gocritic]
      path: trace.go
    # interceptor_test tests a lot of data structure equality so naturally there are
    # a lot of duplications
    - path: interceptor_test.go
      linters: [dupl]
